---
abstract: 'Digest your protein substrates with customizable specificity'
author:
  - 'Bruno Vecchi <vecchi.b gmail.com>'
generated_by: 'Dist::Zilla version 1.100160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-Protease
requires:
  Carp: 0
  ExtUtils::MakeMaker: 6.11
  Memoize: 0
  Modern::Perl: 0
  Moose: 0.98
  MooseX::ClassAttribute: 0.12
  MooseX::Types::Moose: 0
  Test::Exception: 0
  Test::More: 0.88
  Test::Warn: 0
  YAML: 0
  autodie: 2.00
  namespace::autoclean: 0
resources:
  repository: http://github.com/brunoV/bio-protease/
version: 1.100470
